services:
  # mysql:
  #   image: mysql:5.7
  #   container_name: mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: facelog_db
  #   volumes:
  #     - mysql-vol:/var/lib/mysql
  #   networks:
  #     - facelog-network
  #   ports:
  #     - 3306:3306
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
  #     interval: 10s
  #     timeout: 20s
  #     retries: 10
  #     start_period: 60s
  #   restart: always

  facelog-app:
    build:
      context: .
    container_name: facelog-container-local
    ports:
      - 8000:8000
    networks:
      - facelog-network
    volumes:
      - facelog-vol:/app/database/
      - facelog-media:/app/media/
    restart: always
    # depends_on:
    #   mysql:
    #     condition: service_healthy  # This ensures Django starts only after MySQL is ready

networks:
  facelog-network:

volumes:
  facelog-vol:
  facelog-media:
  # mysql-vol:
